### ISSUE TITLE
param in svdb not called in shell 

### ISSUE THREAD

**Issue by nnneeennn** [hydra-genetics/cnv_sv#152]
https://github.com/hydra-genetics/cnv_sv/blob/6523a5ae2101f2bad98d704b28dfc544d9437c4a/workflow/rules/svdb.smk#LL17C9-L17C64

in svdb merge the overlap param is not referenced in the shell command. 
--overlap {params.overlap} 
should be added to the command 

furthermore it might also be helpful to add params and flag for breakend distance 
--bnd_distance {params.bnd_distance}

bnd_distance=config.get("svdb_merge", {}).get("bnd_distance", 10000),

**Comment by padraicc** [comment]
Addressed the missing overlap and extra in #165.
