### ISSUE TITLE
Option of not inputing tumor content/purity in cnvkit_call

### ISSUE THREAD

**Issue by elleira** [hydra-genetics/cnv_sv#154]
As of now there is always a `--purity` setting in cnvkit_call. There should be an option not to include that parameter since default is not the same as `--purity 1.0`
https://cnvkit.readthedocs.io/en/stable/pipeline.html#calling-methods

**Comment by maehler** [comment]
From the cnvkit source, it does seem like setting the purity to 1 is the same as not specifying it at all:

https://github.com/etal/cnvkit/blob/bd533c33931a76b2373c4b053cdcb69c166b91b6/cnvlib/call.py#L37-L50

However, it would be much more clear to be able to set the purity as missing to clearly indicate that this information is not available. I'm working on a this.
